### ISSUE TITLE
Feature request: Handle higher traffic

### ISSUE THREAD

**Issue by ku3o** [OriginalUtkin/Currency-Converter#1]
Hello Kirill, 

I'm Jakub, a software engineer, and a manager from Kiwi and I have some additional feature request for your project.

## Current situation

The usage of the external provider for currency rate sounds reasonable, but there are some drawbacks to it:
- In a case, the provider will be down we cannot perform currency conversion because we cannot connect to the provider.
- The expected traffic is more than 100 requests/hour that the [current solution supports](https://github.com/OriginalUtkin/Currency-Converter/blob/master/API.py#L74).

## Feature request description

Can you implement some caching that can cover for some occasional downtime of the external provider and increase rate limit of your API?

We accept some reasonable inaccuracy caused by currency rates by caching. For caching a lot of time we internally use [Redis](https://redis.io/) key-value storage service. Feel free to use it too in your project.

---
You can ping me here in case you have more question regarding the feature. Also please ping me when you are done.

**Comment by OriginalUtkin** [comment]
Thank you for opening 'feature request'  to my project.
I dunno why I have never heard about redis before. What a powerful one!
Final version was uploaded to master branch. I'm still reading about redis and playin' with it, so existing solution could be probably changed later. 
But problem isn't solved completely. If you run program with following arguments:
```
./currency-converter --input_currency <currency code> --amount <amount_value>
```
it will send more than 100 requests (~121 to be precise ). Therefore, I'm still using a list with [often usable currencies](https://github.com/OriginalUtkin/Currency-Converter#input-parameters)  for  solving that.

If you have some other suggestions for improvement , just let me know :)
